title: Processing, Data, and Methods
author: Vince
description: >-

  Looper as a sample processing framework.
  Brain feminization via methylation, PCBs and autism as initial datasets.
  Bisulfite sequencing and chromatin accessibility as experimental methods.

keywords:
  - Bisulfite
  - Methylation
  - Acetylation
  - PCB
  - Autism

style: gdidefault

# This is where your slides will be found, in the _slides/ folder.
# Number them in sequence
collections:
  - slides

# Don't change these. Change values in _staging.yml and _publish.yml appropriately.
source: source
baseurl: ""
url: ""
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true
  hard_wrap: false
